languages:
  python:
  - title: My first college project! BU Menu Scrapper.
    url: "/projects/BU-Menu-Scrapper/"
    date: 2025-01-12
  - title: Smart Clicker (Previously Windows-Autoclicker)
    url: "/projects/Smart-Clicker/"
    date: 2024-08-21
  - title: My first project! Source finder.
    url: "/projects/source-finder/"
    date: 2021-02-28
  java:
  - title: Learn Java for FTC
    url: "/projects/Java-For-FTC/"
    date: 2025-04-29
  ftc sdk:
  - title: Learn Java for FTC
    url: "/projects/Java-For-FTC/"
    date: 2025-04-29
