languages:
  python:
  - title: My first college project! BU Menu Scrapper.
    url: "/projects/source-finder/"
    date: 2025-01-12
  - title: My first project! Source finder.
    url: "/projects/source-finder/"
    date: 2021-02-28
